### PR TITLE
Initialised Swift Package Manager with Alamofire dependency for inter…

### PR DESCRIPTION
**Pull request by akanksharma**
Initialised Swift Package Manager with Alamofire dependency for internal dependency management

### CODE REVIEW

**Review by ygit — DISMISSED** [review]
Looks good to merge 👏🎉

**Comment by ygit** [comment]
@akanksharma  A small conflict has crept in, check it out

**Review by ygit — APPROVED** [review]
Looks good to merge 🎉

**Review by Viranchee — APPROVED** [review]
Looks good 👌

**Pull request merged**
