### PR TITLE
updated ReadMe

### PR DESCRIPTION
**Pull request by ygit**
added info on Project roadmap

### CODE REVIEW

**Review by Viranchee — APPROVED** [review]
looks good :)

**Comment by ygit** [comment]
@tlimaye91 @Ruchit-Shah @Yash1599 Can anyone of you review this PR?

**Comment by ygit** [comment]
@akanksharma @BuckyBoy6399 Can anyone of you complete the Review required to Merge this PR?

**Review by akanksharma — APPROVED** [review]
Looks good to merge🎉

**Pull request merged**
